name: climate_confluence
description: An app for Climate Confluence
version: 0.0.1+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:
  auth_buttons: ^3.0.2
  bloc: ^8.1.4
  bloc_concurrency: ^0.2.5
  cloud_firestore: ^4.17.5
  cloud_firestore_odm: ^1.0.0-dev.84
  firebase_auth: ^4.19.5
  firebase_core: ^2.31.0
  firebase_storage: ^11.7.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  go_router: ^14.1.1
  google_sign_in: ^6.2.1
  injectable: ^2.4.1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  toasty_box: ^1.0.4
  uuid: ^4.4.0

dependency_overrides:
  meta: ^1.12.0

dev_dependencies:
  bloc_test: ^9.1.7
  build_runner: ^2.4.10
  cloud_firestore_odm_generator: ^1.0.0-dev.85
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.3
  go_router_builder: ^2.6.2
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
