// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwFHY4pM9GejGMZhY1gBGhd39hkt99pLI',
    appId: '1:91286137648:web:3e57903c4713b8696976f5',
    messagingSenderId: '91286137648',
    projectId: 'climate-confluence',
    authDomain: 'climate-confluence.firebaseapp.com',
    storageBucket: 'climate-confluence.appspot.com',
    measurementId: 'G-DSSSQJBPEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuL1_UOn942XL8P5zaIz8C69-Bx2iDnps',
    appId: '1:91286137648:android:dd42074d48086fd66976f5',
    messagingSenderId: '91286137648',
    projectId: 'climate-confluence',
    storageBucket: 'climate-confluence.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdj4deeXDynDkq33lWkmpB4N7JeeiyJ_8',
    appId: '1:91286137648:ios:dc1dd31206ae5ec66976f5',
    messagingSenderId: '91286137648',
    projectId: 'climate-confluence',
    storageBucket: 'climate-confluence.appspot.com',
    androidClientId: '91286137648-ob604tj8a41p64rjvnvk62atmiu74qa2.apps.googleusercontent.com',
    iosClientId: '91286137648-05gc5tgr5ecqv2g0utq06abpp46edccg.apps.googleusercontent.com',
    iosBundleId: 'io.github.amansikarwar.climateConfluence',
  );

}